### ISSUE TITLE
About polar representation

### ISSUE THREAD

**Issue by Shadow581** [Chen-yuiyui/GeoSegNet#1]
Equations (5) and (6) maybe wrong?
The Spherical coordinate system: https://en.wikipedia.org/wiki/Spherical_coordinate_system

**Comment by Chen-yuiyui** [comment]
> Equations (5) and (6) maybe wrong? The Spherical coordinate system: https://en.wikipedia.org/wiki/Spherical_coordinate_system

Please review fig.5. We didn't use the traditional spherical coordinate system, In fact, we use pi/2- θ, which is caculated by arctan(z/√￣（x^2+y^2)）.  And we call them named relative angle.

,

**Comment by Shadow581** [comment]
> > Equations (5) and (6) maybe wrong? The Spherical coordinate system: https://en.wikipedia.org/wiki/Spherical_coordinate_system
> 
> Please review fig.5. We didn't use the traditional spherical coordinate system, In fact, we use pi/2- θ, which is caculated by arctan(z/√￣（x^2+y^2)）. And we call them named relative angle.
> 
> ,

OK, it's my issue. And thank you for your great work.
